check  process  risk_monitor  with  pidfile  /run/ig/risk_monitor.pid
start  program  =  "/usr/bin/sh /opt/version/lawson/Monitor/version/script/start_risk_monitor.sh"
stop  program  =  "/usr/bin/sh /opt/version/lawson/Monitor/version/script/stop_risk_monitor.sh"